package com.example.user.mobdevassignment;

public final class TipsInfo {

    public static final String[] TITLES =
            {
                    "How to Take care of your phone",
                    "How to Take care of your laptop"
            };

    public static final String[] DIALOGUE =
            {
                    "1) Don't abuse the phone. You’ve invested good money in your phone, so you expect it to last a long time. The thing is, even though your cell phone is of high quality, there is still a chance that it will break apart and stop working, especially if you don’t take good care of it. Because of this, it is imperative that you take the necessary precautions to ensure that your phone is kept in tiptop condition. Here are the things that you need to know about taking care of your cell phone. \n"+
                    "2) Keep it safe at all times. Like any other electronic device, you need to handle your phone with utmost care. Keep it in a secure place at all times. Do not leave it lying around for kids or pets to toy with. One of the best ways to protect your phone is to store it in a durable cell phone case. Cell phone accessories, like cool cell phone covers, can be purchased for a cheap price in many online stores. But, make sure you go for quality and reasonable price at the same time so that the protective cover is strong enough to do the job of protecting your phone efficiently.\n"+
                    "3) Don’t drop your phone. One of the most common causes of damage of cell phones is dropping it. To prevent this from happening, always hold on to your phone tightly. It would be a good idea to make use of a cell phone lanyard so that you can wear your cell phone around your neck and not worry about dropping it on the ground accidentally. Like other cell phone accessories, cell phone lanyards can also be bought via the online route.\n"+
                    "4) Avoid moisture and heat. Do not subject your phone to extreme temperature changes, and particularly to strong heat. Avoid placing it near heat sources like the stove, furnace, chimney, and under the sun. Don’t leave it out in the cold, either. Avoid getting it near a source of moisture. All forms of liquids should be kept a good distance away from your phone. Do not drink or eat while using your phone to avoid accidental spillage. Don’t put your phone near any body of water, like the sea or swimming pool. Cell phones can be damaged even by slight dampness. If ever your phone becomes wet, save it by turning it off, removing the parts like SIM card and battery, and by drying the mechanisms using a clean absorbent towel. Always have a waterproof bag handy so that you can slip your phone inside it in case it rains.\n"+
                    "5) Clean it properly. Whatever you do, never use a spray bottle to clean your phone. You should, instead, use a cotton swab dipped in alcohol and touch it lightly over the keypad. Remember to use this only on the exterior part of the phone and never inside. For touch-screen phones, you might want to avoid alcohol, and instead use a soft, lint-free cloth for further protection\n"+
                    "6) Protect it from theft. Damage in the cell phone’s mechanism is not the only thing that can take your phone away from you. It’s also possible that someone might steal your phone, so guard it at all times and protect it just like you would with any of your valuables.",

                    "1) Keep the battery cool. Today's lithium batteries wear out no matter what you do, but you can postpone the inevitable. Avoid heat and use the battery as little as possible. If you're going to be running on AC power for awhile, shut down or hibernate the computer, remove the battery, and work without it.\n"+
                    "2) Be careful about eating and drinking. Spill coffee on your desktop keyboard, and you'll have to spend $15 on a generic replacement you can plug in yourself. Spill it on your laptop keyboard, and you could short out the motherboard. I'll admit that I use my laptop in cafes just like everyone else, but I put my tea as far from the electronics as my table allows.\n"+
                    "3) When home, turn it into a desktop. You don't always need portability. When working at your desk,plug in a full-sized monitor, keyboard, and mouse. Not only does this get around the food and beverage problem discussed above, but it protects items far more valuable than your laptop--your arms, hands, and eyes. You can't set up a proper, ergonomic working environment with a small keyboard attached to a small monitor."+
                    "4) Find the right carrying case. Before taking it on the road, pack the laptop properly. Depending on your carrying preferences, look for a carrying case, backpack, or shoulder bag with a padded section designed especially for a laptop. (I use a backpack because the even distribution of weight is better for my spine.)\n"+
                    "5) Clean the keyboard properly. When keys starts sticking, it's time for a cleaning. Shut down the PC. Keep it open as you turn it upside-down and very gently tap on the back so that crumbs fall out. Then use a can of compressed air (you can buy this at any computer store for a few dollars) to blow out whatever is still stuck. Be sure to read the instructions on the can, first. Then turn the PC upside-down and tap it gently again to get the last bits out.\n"+
                    "6) Clean the screen when it needs it. If you can't see the email for the dirt, it's time to do a little cleaning. Start with a dry, microfiber cloth--the sort you get at an optometrist's office (you can also buy them at photo and computer stores). Move it in circular motions. Be gentle, but apply slight pressure on particularly stubborn spots. If that doesn't clean the screen, make your own cleaning solution by mixing distilled water (make sure it's distilled) and white vinegar in equal proportions into a spray bottle. Turn off your laptop. Spray this mixture lightly onto the microfiber cloth, not onto the monitor. Wipe as described above, then wait ten minutes before booting up."


            };
}
